name: gender_citation_gap_dion_et_al
channels:
  - conda-forge
  - R
  - defaults
dependencies:
  - jupytext==1.14.2
  - r-base=4.2.1
  - r-tidyverse=1.3.2
  - r-foreign=0.8
  - r-irdisplay=1.1
  - r-irkernel=1.3.1
  - r-optimx=2022_4.30
  - r-rms=6.4_0
  - r-kableextra=1.3.4
